/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/_Attributes/ReplayPreparerIgnoreAttribute.cs
/// </summary>
using System;

namespace UltimateReplay
{
    [AttributeUsage(AttributeTargets.Class)]
    public sealed class ReplayPreparerIgnoreAttribute : Attribute
    {
    // Empty class
    }
}