/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/Stream/Source/ReplayStreamSource_FromFile.cs
/// </summary>
using System.IO;
using UnityEngine;

/// <summary>
/// Declarations have been stripped because they were part of the internal implementation
/// </summary>
namespace UltimateReplay.Storage
{
}