/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/Stream/IReplayTokenSerialize.cs
/// </summary>
using System;
using System.Collections.Generic;

namespace UltimateReplay.Storage
{
    public interface IReplayTokenSerialize
    {
    }
}