/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/Stream/ReplayCompressStream.cs
/// </summary>
using System.IO;
using System.IO.Compression;

namespace UltimateReplay.Storage
{
}