/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/Stream/ReplayToken.cs
/// </summary>
using System;
using System.Collections.Generic;
using System.Reflection;

namespace UltimateReplay.Storage
{
    public struct ReplayToken
    {
        // Public
        public static readonly ReplayToken invalid;
        // Properties
        public bool IsValid
        {
            get
            {
                return identifier != null && (field != null || property != null);
            }
        }

        public string Identifier
        {
            get
            {
                return identifier;
            }
        }

        public bool IsOptional
        {
            get
            {
                return isOptional;
            }
        }

        public Type ValueType
        {
            get
            {
                // Get field type
                if (field != null)
                    return field.FieldType;
                // Get property type
                if (property != null)
                    return property.PropertyType;
                return null;
            }
        }

        // Constructor
        internal ReplayToken(string identifier, FieldInfo field, bool isOptional)
        {
            this.identifier = identifier;
            this.field = field;
            this.property = null;
            this.isOptional = isOptional;
        }

        internal ReplayToken(string identifier, PropertyInfo property, bool isOptional)
        {
            this.identifier = identifier;
            this.property = property;
            this.field = null;
            this.isOptional = isOptional;
        }

        // Methods
        public object FetchValue(object instance) => throw new System.NotImplementedException();
        public void StoreValue(object instance, object value) => throw new System.NotImplementedException();
        public static ReplayToken Create(string fieldOrPropertyName, Type declaringType, bool isOptional = false) => throw new System.NotImplementedException();
        public static ReplayToken Create(FieldInfo field, bool isOptional = false) => throw new System.NotImplementedException();
        public static ReplayToken Create(PropertyInfo property, bool isOptional = false) => throw new System.NotImplementedException();
        public static IEnumerable<ReplayToken> Tokenize(object instance) => throw new System.NotImplementedException();
        public static IEnumerable<ReplayToken> Tokenize(Type type) => throw new System.NotImplementedException();
        public static IEnumerable<ReplayToken> Tokenize<T>() => throw new System.NotImplementedException();
    }
}