/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Lifecycle/ReplayObjectResourcesLifecycleProvider.cs
/// </summary>
using System;
using UnityEngine;

namespace UltimateReplay.Lifecycle
{
    [Serializable]
    public class ReplayObjectResourcesLifecycleProvider : ReplayObjectLifecycleProvider
    {
        // Public
        public string resourcesPath = "MyReplayPrefab";
        public bool allowPooling = true;
        public bool asyncLoadOnStartup = true;
        // Properties
        public override bool IsAssigned
        {
            get
            {
                return string.IsNullOrEmpty(resourcesPath) == false;
            }
        }

        public override string ItemName
        {
            get
            {
                return resourcesPath;
            }
        }

        public override ReplayIdentity ItemPrefabIdentity
        {
            get
            {
                EnsurePrefabIsLoaded();
                return replayResourcesPrefab != null ? replayResourcesPrefab.PrefabIdentity : ReplayIdentity.invalid;
            }
        }

        public override ReplayObject InstantiateReplayInstance(Vector3 position, Quaternion rotation) => throw new System.NotImplementedException();
        public ReplayObject InstantiateReplayInstance() => throw new System.NotImplementedException();
        public override void DestroyReplayInstance(ReplayObject replayInstance) => throw new System.NotImplementedException();
    }
}