/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Lifecycle/ReplayObjectPool.cs
/// </summary>
using System;
#if !ULTIMATEREPLAY_DISABLE_UNITYPOOL
using UnityEngine.Pool;

#endif
namespace UltimateReplay.Lifecycle
{
}