/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Lifecycle/ReplayObjectLifecycleProvider.cs
/// </summary>
using System;
using UnityEngine;

namespace UltimateReplay.Lifecycle
{
    [Serializable]
    public abstract class ReplayObjectLifecycleProvider : ScriptableObject
    {
        // Properties
        public abstract bool IsAssigned
        {
            get;
        }

        public abstract string ItemName
        {
            get;
        }

        public abstract ReplayIdentity ItemPrefabIdentity
        {
            get;
        }

        // Methods
        public abstract ReplayObject InstantiateReplayInstance(Vector3 position, Quaternion rotation);
        public abstract void DestroyReplayInstance(ReplayObject replayInstance);
        public static void DestroyReplayObject(ReplayObject obj) => throw new System.NotImplementedException();
    }
}