/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/ComponentData/ReplayMethods.cs
/// </summary>
using System;
using System.Collections.Generic;
using System.Reflection;
using UltimateReplay.Storage;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif
namespace UltimateReplay
{
}