/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: DLCToolkit.dll
/// From source file: Assets/Ultimate DLC Toolkit/Scripts/Runtime/Toolkit/DRM/DefaultDRMServiceProvider.cs
/// </summary>
using System;
using System.IO;
using UnityEngine;

namespace DLCToolkit.DRM
{
    /// <summary>
    /// A DRM service provider that supports editor local DRM, steamworks, and google play DRM services.
    /// </summary>
    public sealed class DefaultDRMServiceProvider : IDRMServiceProvider
    {
        // Public
        /// <summary>
        /// The path where DLC content will be stored in editor mode.
        /// The editor will scan this folder for DLC content automatically.
        /// </summary>
        public string editorContentPath = "DLC";
        // Methods
        /// <summary>
        /// Get the DRM provider for the current platform.
        /// </summary>
        /// <returns></returns>
        /// <exception cref = "NotSupportedException"></exception>
        public IDRMProvider GetDRMProvider() => throw new System.NotImplementedException();
    }
}