/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/Memory/ReplayMemoryStorage.cs
/// </summary>
using System;
using System.Collections.Generic;
using System.IO;

namespace UltimateReplay.Storage
{
    public sealed class ReplayMemoryStorage : ReplayStorage
    {
        // Properties
        public override bool CanRead
        {
            get => throw new System.NotImplementedException();
        }

        public override bool CanWrite
        {
            get => throw new System.NotImplementedException();
        }

        public override float Duration
        {
            get => throw new System.NotImplementedException();
        }

        public override int MemorySize
        {
            get => throw new System.NotImplementedException();
        }

        public override int SnapshotSize
        {
            get => throw new System.NotImplementedException();
        }

        public override int IdentitySize
        {
            get => throw new System.NotImplementedException();
        }

        public float RollingBufferDuration
        {
            get => throw new System.NotImplementedException();
        }

        // Constructor
        public ReplayMemoryStorage(string replayName = null, float rollingBufferDuration = -1f): base(default) => throw new System.NotImplementedException();
        // Methods
        public override ReplaySnapshot FetchSnapshot(float timeStamp) => throw new System.NotImplementedException();
        public override ReplaySnapshot FetchSnapshot(int sequenceID) => throw new System.NotImplementedException();
        public override void StoreSnapshot(ReplaySnapshot state) => throw new System.NotImplementedException();
        public override void Prepare(ReplayStorageAction mode) => throw new System.NotImplementedException();
        protected override void OnDispose() => throw new System.NotImplementedException();
        public bool SaveToFile(string replayFile) => throw new System.NotImplementedException();
        public ReplayAsyncOperation SaveToFileAsync(string replayFile) => throw new System.NotImplementedException();
        public bool LoadFromFile(string replayFile) => throw new System.NotImplementedException();
        public ReplayAsyncOperation LoadFromFileAsync(string replayFile) => throw new System.NotImplementedException();
        public byte[] ToBytes() => throw new System.NotImplementedException();
        public bool FromBytes(byte[] bytes) => throw new System.NotImplementedException();
    }
}