/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/ReplayBlendShape.cs
/// </summary>
using System;
using System.Collections.Generic;
using UltimateReplay.Formatters;
using UnityEngine;

namespace UltimateReplay
{
    public class ReplayBlendShape : ReplayRecordableBehaviour
    {
        // Public
        public SkinnedMeshRenderer observedSkinnedMeshRenderer;
        public bool interpolate = true;
        // Methods
        public void Start() => throw new System.NotImplementedException();
        protected override void Reset() => throw new System.NotImplementedException();
        protected override void OnReplayReset() => throw new System.NotImplementedException();
        protected override void OnReplayUpdate(float t) => throw new System.NotImplementedException();
        public override void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public override void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
    }
}