/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/ReplayTrailRenderer.cs
/// </summary>
using System;
using System.Collections.Generic;
using UltimateReplay.Serializers;
using UnityEngine;

namespace UltimateReplay
{
    public class ReplayTrailRenderer : ReplayRecordableBehaviour
    {
        // Types
        [Flags]
        public enum ReplayTrailRendererFlags
        {
            None = 0,
            Interpolate = 1 << 1,
        }

        // Public
        public TrailRenderer observedTrailRenderer = null;
        [HideInInspector]
        public ReplayTrailRendererFlags updateFlags;
        public bool clearOnReplayEnd = true;
        // Methods
        public void Start() => throw new System.NotImplementedException();
        protected override void OnReplayReset() => throw new System.NotImplementedException();
        protected override void OnReplayEnd() => throw new System.NotImplementedException();
        protected override void OnReplayUpdate(float t) => throw new System.NotImplementedException();
        public override void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public override void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
    }
}