/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/ReplayRiggedHumanoid.cs
/// </summary>
using UltimateReplay.Formatters;
using UnityEngine;

namespace UltimateReplay
{
    public sealed class ReplayRiggedHumanoid : ReplayRecordableBehaviour
    {
        // Public
        public Animator observedAnimator;
        public Transform observedRoot;
        // Properties
        public override ReplayFormatter Formatter
        {
            get => throw new System.NotImplementedException();
        }

        public RecordFullAxisFlags ReplayBodyPosition
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public RecordPrecision BodyPositionPrecision
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public RecordFullAxisFlags ReplayBodyRotation
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public RecordPrecision BodyRotationPrecision
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public RecordPrecision MuslceValuesPrecision
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        // Methods
#if UNITY_EDITOR
        private void OnValidate()
        {
            // Update serialize flags
            UpdateSerializeFlags();
        }
#endif
        protected override void Reset() => throw new System.NotImplementedException();
        protected override void Awake() => throw new System.NotImplementedException();
        protected override void OnReplayReset() => throw new System.NotImplementedException();
        protected override void OnReplayStart() => throw new System.NotImplementedException();
        protected override void OnReplayUpdate(float t) => throw new System.NotImplementedException();
        public override void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public override void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
    }
}