/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: DLCToolkit.dll
/// From source file: Assets/Ultimate DLC Toolkit/Scripts/Runtime/Toolkit/Exception/DLCNotLoadedException.cs
/// </summary>
using System;

namespace DLCToolkit
{
    /// <summary>
    /// An exception thrown when DLC content is trying to be accessed but the DLC is not loaded.
    /// </summary>
    public sealed class DLCNotLoadedException : Exception
    {
        // Constructor
        /// <summary>
        /// Create new instance.
        /// </summary>
        public DLCNotLoadedException(): base(default) => throw new System.NotImplementedException();
        /// <summary>
        /// Create new instance.
        /// </summary>
        /// <param name = "message">The exception message</param>
        public DLCNotLoadedException(string message): base(default) => throw new System.NotImplementedException();
    }
}