/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: DLCToolkit.dll
/// From source file: Assets/Ultimate DLC Toolkit/Scripts/Runtime/Toolkit/Exception/DLCNotAvailableException.cs
/// </summary>
using System;

namespace DLCToolkit
{
    /// <summary>
    /// An exception thrown when DLC is not available upon request.
    /// </summary>
    public sealed class DLCNotAvailableException : Exception
    {
        // Constructor
        /// <summary>
        /// Create a new instance.
        /// </summary>
        public DLCNotAvailableException(): base(default) => throw new System.NotImplementedException();
        /// <summary>
        /// Create a new instance.
        /// </summary>
        /// <param name = "message">The exception message</param>
        public DLCNotAvailableException(string message): base(default) => throw new System.NotImplementedException();
    }
}