/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayRecordOptions.cs
/// </summary>
using System;
using UnityEngine;

namespace UltimateReplay
{
    /// <summary>
    /// A number of options that can be used to control the record behaviour.
    /// </summary>
    [Serializable]
    public sealed class ReplayRecordOptions : ISerializationCallbackReceiver
    {
        // Public
        /// <summary>
        /// The minimum allowable record frame rate.
        /// </summary>
        public const float MinRecordFPS = 1;
        /// <summary>
        /// The maximum allowable record frame rate.
        /// </summary>
        public const float MaxRecordFPS = 60;
        /// <summary>
        /// The default fps value for record operations.
        /// </summary>
        public const float DefaultRecordFPS = 12f;
        // Properties
        /// <summary>
        /// The target record frame rate.
        /// Higher frame rates will result in more storage consumption but better replay accuracy.
        /// </summary>
        public float RecordFPS
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        /// <summary>
        /// The update method used to update the record operation.
        /// Used for compatibility with other systems that update objects in other update methods such as LateUpdate.
        /// </summary>
        public ReplayUpdateMode RecordUpdateMode
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        // Methods
        void ISerializationCallbackReceiver.OnBeforeSerialize() => throw new System.NotImplementedException();
        void ISerializationCallbackReceiver.OnAfterDeserialize() => throw new System.NotImplementedException();
    }
}