/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/Formatters/ReplayParentChangeFormatter.cs
/// </summary>
using System;
using UnityEngine;

namespace UltimateReplay.Formatters
{
    public sealed class ReplayParentChangeFormatter : ReplayFormatter
    {
        // Properties
        public ReplayIdentity ParentIdentity
        {
            get
            {
                return parentIdentity;
            }

            set
            {
                parentIdentity = value;
            }
        }

        public bool HasParent
        {
            get
            {
                return parentIdentity.ID != 0;
            }
        }

        // Methods
        public override void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public override void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
        public void UpdateFromTransform(Transform from) => throw new System.NotImplementedException();
        public void SyncTransform(Transform sync, ReplayScene scene) => throw new System.NotImplementedException();
    }
}