/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/Formatters/ReplayRiggedHumanoidFormatter.cs
/// </summary>
using System;
using System.Collections.Generic;
using UnityEngine;

namespace UltimateReplay.Formatters
{
    public sealed class ReplayRiggedHumanoidFormatter : ReplayFormatter
    {
        public Vector3 BodyPosition => throw new System.NotImplementedException()public Quaternion BodyRotation => throw new System.NotImplementedException()public IReadOnlyList<float> MuscleValues => throw new System.NotImplementedException()// Methods
        public override void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public override void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
    }
}