/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/Serializers/ReplayPointRendererSerializer.cs
/// </summary>
using System;
using System.Collections.Generic;
using UnityEngine;

namespace UltimateReplay.Serializers
{
    public sealed class ReplayPointRendererSerializer : IReplaySerialize
    {
        // Types
        [Flags]
        public enum ReplayPointRendererSerializeFlags : byte
        {
            None = 0,
            LowPrecision = 1 << 1,
            HalfPrecisionCount = 1 << 2,
        }

        // Properties
        public ReplayPointRendererSerializeFlags SerializeFlags
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public IList<Vector3> Points
        {
            get => throw new System.NotImplementedException();
        }

        // Methods
        public void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
        public void Reset() => throw new System.NotImplementedException();
    }
}