/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/ReplayComponents/Serializers/ReplayMaterialSerializer.cs
/// </summary>
using System;
using UnityEngine;

namespace UltimateReplay.Serializers
{
    public class ReplayMaterialSerializer : IReplaySerialize
    {
        // Types
        [Flags]
        public enum ReplayMaterialSerializeFlags : byte
        {
            None = 0,
            SharedMaterial = 1 << 0,
            Color = 1 << 1,
            MainTextureOffset = 1 << 2,
            MainTextureScale = 1 << 3,
            DoubleSidedGlobalIllumination = 1 << 4,
            GlobalIlluminationFlags = 1 << 5,
        }

        // Properties
        public ReplayMaterialSerializeFlags SerializeFlags
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public Color Color
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public Vector2 MainTextureOffset
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public Vector2 MainTextureScale
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public bool DoubleSidedGlobalIllumination
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        public MaterialGlobalIlluminationFlags GlobalIlluminationFlags
        {
            get => throw new System.NotImplementedException();
            set => throw new System.NotImplementedException();
        }

        // Methods
        public void OnReplaySerialize(ReplayState state) => throw new System.NotImplementedException();
        public void OnReplayDeserialize(ReplayState state) => throw new System.NotImplementedException();
        public void Reset() => throw new System.NotImplementedException();
    }
}