/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Statistics/ReplayStatisticsUtil.cs
/// </summary>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UltimateReplay.Statistics
{
    public static class ReplayStatisticsUtil
    {
        // Methods
        public static decimal GetMemorySizeSmallestUnit(int amount) => throw new System.NotImplementedException();
        public static string GetMemoryUnitString(int amount) => throw new System.NotImplementedException();
        public static string GetByteSizeString(int bytes) => throw new System.NotImplementedException();
    }
}