/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Statistics/ReplayRecordableStatistics.cs
/// </summary>
using System;

namespace UltimateReplay.Statistics
{
    public static class ReplayRecordableStatistics
    {
        // Types
        public struct ReplayObjectStatistics
        {
            // Public
            public int byteSize;
            public int evaluatedComponents;
            public int supressedComponents;
            public bool didSupressComponents;
        }

        // Methods
        public static ReplayObjectStatistics CalculateReplayRecordStorageUsage(ReplayObject replayObject) => throw new System.NotImplementedException();
        public static ReplayObjectStatistics CalculateReplayRecordStorageUsage(params ReplayObject[] replayObjects) => throw new System.NotImplementedException();
        public static int CalculateReplayRecordStorageUsage(ReplayRecordableBehaviour replayBehaviour) => throw new System.NotImplementedException();
        public static int CalculateReplayRecordStorageUsage(params ReplayRecordableBehaviour[] replayBehaviours) => throw new System.NotImplementedException();
        public static void SupressStatisticsDuringEditMode() => throw new System.NotImplementedException();
    }
}