/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/ReplayCleanupUtility.cs
/// </summary>
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Declarations have been stripped because they were part of the internal implementation
/// </summary>
namespace UltimateReplay
{
}