/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/ReplayPlaybackAccuracyReporter.cs
/// </summary>
using System.Collections;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace UltimateReplay
{
}