/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: DLCToolkit.dll
/// From source file: Assets/Ultimate DLC Toolkit/Scripts/Runtime/Toolkit/DLCConfig.cs
/// </summary>
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Declarations have been stripped because they were part of the internal implementation
/// </summary>
namespace DLCToolkit
{
}