/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Storage/ReplayStreamUtility.cs
/// </summary>
using System;
using System.IO;

namespace UltimateReplay.Storage
{
    public static class ReplayStreamUtility
    {
    }
}