/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/StatePreparation/AnimatorPreparer.cs
/// </summary>
using UnityEngine;

namespace UltimateReplay.StatePreparation
{
}