/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/StatePreparation/SerializableType.cs
/// </summary>
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace UltimateReplay.StatePreparation
{
    [Serializable]
    public class SerializableType
    {
        // Properties
        public Type SystemType
        {
            get
            {
                ResolveType();
                return systemTypeInstance;
            }
        }

        // Constructor
        public SerializableType()
        {
        }

        public SerializableType(Type systemType)
        {
            this.assemblyQualifiedTypeName = systemType.AssemblyQualifiedName;
            this.systemTypeInstance = systemType;
        }

        // Methods
        public bool ResolveType() => throw new System.NotImplementedException();
        public static implicit operator SerializableType(Type systemType)
        {
            return new SerializableType(systemType);
        }
    }
}