/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Common/StatePreparation/SerializableType.cs
/// </summary>
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace UltimateReplay.StatePreparation
{
    [Serializable]
    public class SerializableType
    {
        // Properties
        public Type SystemType
        {
            get => throw new System.NotImplementedException();
        }

        // Constructor
        public SerializableType() => throw new System.NotImplementedException();
        public SerializableType(Type systemType) => throw new System.NotImplementedException();
        // Methods
        public bool ResolveType() => throw new System.NotImplementedException();
        public static implicit operator SerializableType(Type systemType)
        {
            return new SerializableType(systemType);
        }
    }
}