/// <summary>
/// This source file was auto-generated by a tool - Any changes may be overwritten!
/// From Unity assembly definition: UltimateReplay.dll
/// From source file: Assets/Ultimate Replay 3.0/Scripts/Runtime/Util/HexConverter.cs
/// </summary>
using System;
using UltimateReplay.Util;

namespace UltimateReplay
{
    public static class HexConverter
    {
        // Methods
        public static string GetHexString(byte[] bytes, int offset, int length) => throw new System.NotImplementedException();
        public static void GetHexValue(byte val, out char a, out char b) => throw new System.NotImplementedException();
        public static void GetHexBytes(string hex, byte[] bytes, int offset) => throw new System.NotImplementedException();
        public static int GetHexValue(char hex) => throw new System.NotImplementedException();
        public static string ToHexString(int value) => throw new System.NotImplementedException();
        public static string ToHexString(float value) => throw new System.NotImplementedException();
        public static int FromHexStringInt32(string hex) => throw new System.NotImplementedException();
        public static float FromHexStringSingle(string hex) => throw new System.NotImplementedException();
    }
}